sudo: required
services:
  - docker
language: java
jdk:
  - openjdk15
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_REPOSITORY=rso/recepti-service:0.0.1-SNAPSHOT
    - IMAGE_NAME=recepti-service
    - IMAGE_TAG=0.0.1-SNAPSHOT
before_install:
  - chmod +x mvnw
script:
  - docker build -t "$DOCKER_USERNAME"/"$DOCKER_REPOSITORY"/"$IMAGE_NAME":"$IMAGE_TAG" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/"$DOCKER_REPOSITORY"/"$IMAGE_NAME":"$IMAGE_TAG"
