sudo: required
services:
  - docker
language: java
jdk:
  - openjdk15
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=recepti-service:0.0.1-SNAPSHOT-$TRAVIS_JOB_NUMBER
before_install:
  - chmod +x mvnw
script:
  - docker build -t "$DOCKER_IMAGE" .
  - docker images
  - docker tag "$DOCKER_IMAGE" $DOCKER_USERNAME/"$DOCKER_IMAGE"
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE"
