sudo: required
services:
  - docker
language: java
jdk:
  - openjdk15
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=recepti-service/recepti-service:0.0.1-SNAPSHOT
script:
  - chmod +x mvnw
  - mvn clean package -U -DskipTests
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
