language: java
jdk:
  - openjdk15
services:
  - docker
before_install:
  - echo "#DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - chmod +x mvnw
script:
  - ./mvnw clean install -DskipTests
  - mvn deploy