server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: recepti-service

  profiles:
    active: dev

  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  cloud:
    consul:
      discovery:
        health-check-path: /check/health
        health-check-interval: 10s
      config:
        watch:
          enabled: true
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /check

  endpoint:
    health:
      show-details: always
    metrics:
      cache:
        time-to-live: 10s