server:
  port: 8081
spring:
  application:
    name: recepti-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"