server:
  port: 8081
spring:
  application:
    name: recepti-service
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-url: http://localhost:8081/check/health
        health-check-interval: 10s
      config:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /check